package com.github.lyokofirelyte.Elysian.MMO;

public enum MMO {

	IS_TREE_FELLING("IS_TREE_FELLING"),
	TREE_FELLER_CD("TREE_FELLER_CD"),
	IS_SUPER_BREAKING("IS_SUPER_BREAKING"),
	SUPER_BREAKER_CD("SUPER_BREAKER_CD"),
	IS_SKY_BLADING("IS_SKY_BLADING"),
	SKY_BLADE_CD("SKY_BLADE_CD"),
	SKY_BLADE_COUNTER("SKY_BLADE_COUNTER"),
	SAVED_ENCHANTS("SAVED_ENCHANTS"),
	IS_CHOPPING("IS_CHOPPING"),
	IS_BLADING("IS_BLADING"),
	INVALID_BLOCKS("INVALID_BLOCKS"),
	IS_MINING("IS_MINING"),
	IS_LIFE_FORCING("IS_LIFE_FORCING"),
	LIFE_FORCE_CD("LIFE_FORCE_CD"),
	IS_TURBO_DRILLING("IS_TURBO_DRILLING"),
	IS_DIGGING("IS_DIGGING"),
	TURBO_DRILL_CD("TURBO_DRILL_CD"),
	HOLY_COOLDOWN("HOLY_COOLDOWN"),
	VAMP_BAR("VAMP_BAR"),
	VAMP_MULT("VAMP_MULT"),
	IS_SOUL_SPLITTING("IS_SOUL_SPLITTING");
	
	MMO(String type){
		this.type = type;
	}
	
	public String type;
}